[project]
name = "mcp-freesound"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "requests",
    "fastapi[standard]>=0.115.12",
    "mcp[cli]>=1.8.1",
    "httpx>=0.28.1",
    "uvicorn>=0.34.2",
	"python-osc>=1.9.3",
    "ffmpeg-python",
    "dotenv",
]
